### PR TITLE
Negate alpha from selection as latest

### PR DESCRIPTION
**Pull request by disaac**
* Removed alpha versions from latest versions.
* Allow explicit selection of alpha versions only.

### CODE REVIEW

**Comment by disaac** [comment]
Unfortunately there are alpha[3-4] that are not available for installation and would need to be negated from the available versions returned from list-remote. Only v0.12.0-alpha1 is an [official alpha release](https://github.com/hashicorp/terraform/releases). Could instead check github for the official release tags instead of assuming all returned from curl are available.

**Comment by iamhsa** [comment]
@disaac Thanks for your PR. AFAIC you're right, exlude alpha versions is a good the solution.

> Could instead check github for the official release tags instead of assuming all returned from curl are available.

It seems a good idea but I think :
- it sould be discussed in [tfutil/tfenv](https://github.com/tfutils/tfenv/issues) and validated by maintainer.
- it will probably break the checksum and the keybase verification (if the get is on github only).

However I'm looking your PR and I don't understand why you check apharegexp in tfenv-use and tfenv-version-name, as a test on apharegexp seems te be egnouth in tfenv-install.
Could you explain ? Perhaps I have missed something.

I work on something based on your PR, I will push a commit soon. Let me know if you think it's pertinent.

**Comment by iamhsa** [comment]
@disaac You can see https://github.com/iamhsa/tfenv/tree/list-remote-alpha-pr1.
By the way I don't know how to push my commits in this PR  :-\

**Comment by iamhsa** [comment]
correction performed upstream

**Pull request closed without merging**
